# Generated by Django 5.1.2 on 2024-10-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('can_view_profile', 'Can View Profile'),)},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='medical_license',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=10, null=True),
        ),
    ]
