# Generated by Django 4.2.16 on 2024-10-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='medical_license',
            new_name='location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
