# Generated by Django 4.2.16 on 2024-10-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_full_name_alter_customuser_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='specialist',
            field=models.CharField(blank=True, choices=[('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Pediatrician', 'Pediatrician'), ('Surgeon', 'Surgeon'), ('General Physician', 'General Physician'), ('Gastroenterologist', 'Gastroenterologist'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
