# Generated by Django 4.2.16 on 2024-10-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
