# Generated by Django 4.2.16 on 2024-10-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0010_chatsession_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='message',
        ),
        migrations.RemoveField(
            model_name='chatsession',
            name='response',
        ),
    ]
